### PR TITLE
Mod Support for circuit networks over clusterio

### PR DESCRIPTION
**Pull request by justarandomgeek**
Add Transmit/Receive Combinators. Transmit combinators are Deciders which also output into txbuffer.txt. Receive Combinators are Constants which replay frames received from external sources via remote calls to receiveFrame and recieveMany.

### CODE REVIEW

**Comment by Danielv123** [comment]
Thanks for the work! I will pull this into my dev branch and see about integrating it.

**Comment by justarandomgeek** [comment]
It is necessary for the transmitter to check every tick, or it may miss pulses from the circuits - these devices are intended to work with pulses, which are only around for a single tick. It is likely that the clusterio client would then read multiple frames at once, which is perfectly fine - they're going into a buffer that feeds a buffer anyway, right?

The inter-game linking is missing because I don't (yet) node.js - I just said I'd do this part, so I did ;)

If two factories send multiple signals, they should be relayed one after another by the node.js master distributing them to worlds - in fifo order as seen by the master, presumably. 

And if the sum of all factories transmits signals faster than any world can play them back, frames are dropped in that world when receiving into it's buffer. It is the transmitting world's responsibility to wait/retransmit as needed.

**Comment by justarandomgeek** [comment]
Yeah, perhaps in a future update frames will get a destination address and only be sent to that world if set. You'll see i have commented out signals for src/dest address - intended for this exact purpose! I just wasn't sure how to assign world IDs at this point, and left that for later.

**Comment by Danielv123** [comment]
I am already delaying the reading of files to every 3 seconds because of problems and stuff, so thats not an issue. There is no need for it to request the signals from the master from the mod, client.js can just ask master every 3 seconds or so. I believe I can do this, but it will take a bit of time as I have a lot of stuff going on this week.

**Comment by justarandomgeek** [comment]
> @Danielv123  
> I will pull this into my dev branch and see about integrating it.

Should I send pullreqs to dev in the future and/or resubmit this one there?

**Comment by Danielv123** [comment]
Since I have to do a bit of work in the devbranch anyways, I just use normal merges so it does not matter. Otherwise, I guess pull requests to dev would be the best.

**Comment by Danielv123** [comment]
Merged into dev.

**Pull request closed without merging**
